#!/bin/bash

# https://github.com/jupyter-widgets/ipyleaflet/issues/212
conda install --no-deps -y -c conda-forge ipyleaflet=0.9.2

jupyter serverextension enable --py nbserverproxy --sys-prefix
jupyter labextension install @jupyter-widgets/jupyterlab-manager@0.38 \
                             @jupyterlab/hub-extension@0.12 \
                             @pyviz/jupyterlab_pyviz@0.6.4 \
                             jupyter-leaflet@0.9.2 \
                             dask-labextension@0.3.0


#EOF
